/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIpages;

import backendHander.DBAppHandler;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.*;

/**
 *
 * @author ADMIN
 */
public class AddIngredient extends javax.swing.JFrame {

    /**
     * Creates new form AddIngredient
     */
    public AddIngredient() {
        initComponents();
        Display();
        jList1.setModel(listModel);
        lbName.setText(StoreItem.ItemName);
        String price = StoreItem.ItemPrice + "";
        lbPrice.setText(price);
        lbCate.setText(StoreItem.category);
        this.setLocationRelativeTo(null);

    }
    private DefaultListModel<String> listModel = new DefaultListModel<>();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_back1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        IngreNameCombo = new javax.swing.JComboBox<>();
        txt_unit = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btn_done = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        lbPrice = new javax.swing.JLabel();
        lbCate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_back1.setBackground(new java.awt.Color(204, 204, 204));
        btn_back1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_back1.setText("Back");
        btn_back1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), null, null));
        btn_back1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel2.setText("Add Ingredient");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Select Ingredient to add");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Input required Unit");

        IngreNameCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        IngreNameCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngreNameComboActionPerformed(evt);
            }
        });

        txt_unit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_unitActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Add Ingredient");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        btn_done.setBackground(new java.awt.Color(204, 204, 204));
        btn_done.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_done.setText("Done");
        btn_done.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), null, null));
        btn_done.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_doneActionPerformed(evt);
            }
        });

        btn_add.setBackground(new java.awt.Color(204, 204, 204));
        btn_add.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_add.setText("Add");
        btn_add.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), null, null));
        btn_add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        jLabel1.setText("Menu Name :  ");

        jLabel3.setText("Price : ");

        jLabel7.setText("Category :");

        lbName.setText("hi");

        lbPrice.setText("jLabel8");

        lbCate.setText("10");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btn_back1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addGap(83, 83, 83)
                .addComponent(jLabel5)
                .addGap(139, 139, 139)
                .addComponent(jLabel6))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IngreNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addComponent(lbName))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(49, 49, 49)
                        .addComponent(lbPrice))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(29, 29, 29)
                        .addComponent(lbCate)))
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_unit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(92, 92, 92)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(581, 581, 581)
                .addComponent(btn_done, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_back1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(IngreNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lbName))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(lbPrice))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(lbCate)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_unit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_done, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Display() {
        try {
            DBAppHandler db = new DBAppHandler();
            List<List<Object>> menuItems = db.getIngre();
            DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();
            for (List<Object> row : menuItems) {
                int itemId = (int) row.get(0);
                String itemName = row.get(1).toString();
                comboBoxModel.addElement(itemId + " - " + itemName);
            }
            IngreNameCombo.setModel(comboBoxModel);
        } catch (Exception e) {
            System.out.println("Failed to populate combo box: " + e.getMessage());
        }
    }
    private void btn_back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back1ActionPerformed
        // TODO add your handling code here:
        Add_New_Item.main(null);
        this.dispose();
    }//GEN-LAST:event_btn_back1ActionPerformed

    private void txt_unitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_unitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_unitActionPerformed

    private void btn_doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_doneActionPerformed
        // TODO add your handling code here:
        DBAppHandler db = new DBAppHandler();
        String cateName = StoreItem.category;
        String ItemName = StoreItem.ItemName;
        Double price = StoreItem.ItemPrice;
//=========================old =============================
//        List<Map<Integer, Integer>> menuIng = new ArrayList<>();
//        Map<Integer, Integer> ingredients = new HashMap<>();
//        int IngreId = StoreItem.ingreId;
//        int unit = StoreItem.unit;
//        if (IngreId == 0 || unit == 0) {
//            JOptionPane.showMessageDialog(this, "Must add at least one ingredient with a valid quantity!", "Input Error", JOptionPane.WARNING_MESSAGE);
//            return;
//        }
//        ingredients.put(IngreId, unit);
//        menuIng.add(ingredients);
//
//        if (cateName == null || cateName.trim().isEmpty() || ItemName == null || ItemName.trim().isEmpty() || Double.compare(price, 0.00) == 0) {
//            JOptionPane.showMessageDialog(this, "Must Input Ingredient and quantity", "Please Input", JOptionPane.WARNING_MESSAGE);
//            return;
//        }

//=======================  end old==================================================
        ArrayList<Map<Integer, Integer>> menuIngg = StoreItem.getIngredients();
        if (StoreItem.getIngredients().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Must add at least one ingredient with a valid quantity!", "Input Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (cateName == null || cateName.trim().isEmpty() || ItemName == null || ItemName.trim().isEmpty() || Double.compare(price, 0.00) == 0) {
            JOptionPane.showMessageDialog(this, "Must Input Ingredient and quantity", "Please Input", JOptionPane.WARNING_MESSAGE);
            return;
        }
        db.add(cateName, ItemName, price, menuIngg);
        StoreItem.clearIngredients();

//        new Dashboard().setVisible(true);
        Dashboard.main(null);

        this.dispose();
    }//GEN-LAST:event_btn_doneActionPerformed


    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:

        String name = IngreNameCombo.getSelectedItem().toString().trim();
        String qty = txt_unit.getText().trim();
        int Unit;
        try {
            Unit = Integer.parseInt(qty);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter the ingredient unit.(Input Number Only!!)", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (Unit > 1000) {
            JOptionPane.showMessageDialog(this, "Ingredient must less then 1000g", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (isExist(name)) {
            JOptionPane.showMessageDialog(this, "this ingredient is already added", "Duplicate Ingredient", JOptionPane.WARNING_MESSAGE);
            return;
        }

//        int cfAddIngre = JOptionPane.showConfirmDialog(this, "Are you sure you want to add " + name + " with qty " + Unit + "g to menu " + StoreItem.ItemName,
//                
//                "Note: You cannnot remove when you aleady added!!!",
//      
//                JOptionPane.YES_NO_OPTION,
//                JOptionPane.QUESTION_MESSAGE);
        String[] parts = name.split(" - ", 2);
        String onlyName = (parts.length > 1) ? parts[1] : parts[0];

        JLabel message = new JLabel("<html>Are you sure you want to add "
                + onlyName + " with qty " + Unit + "g to menu " + StoreItem.ItemName
                + "<font color='red'><br>Note: You cannot remove it once you added!</font></html>");
        int cfAddIngre = JOptionPane.showConfirmDialog(
                null, message, "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (cfAddIngre == JOptionPane.YES_OPTION) {
            String getIngreId = IngreNameCombo.getSelectedItem().toString();
            String[] splitData = getIngreId.split(" - ");
            if (splitData.length >= 1) {
                try {
                    int selectedId = Integer.parseInt(splitData[0]);
//                StoreItem.ingreId = selectedId;
                    StoreItem.addIngredient(selectedId, Unit);
//                System.out.println(StoreItem.ingreId);
                } catch (NumberFormatException e) {
                    System.out.println("Error");
                }
            }
            String ItemInlist = name + " | Unit: " + qty + "g";
            listModel.addElement(ItemInlist);
            txt_unit.setText("");
        }

//        StoreItem.unit = Unit;
//        get ingredient Id
//        String getIngreId = IngreNameCombo.getSelectedItem().toString();
//        String[] splitData = getIngreId.split(" - ");
//        if (splitData.length >= 1) {
//            try {
//                int selectedId = Integer.parseInt(splitData[0]);
////                StoreItem.ingreId = selectedId;
//                StoreItem.addIngredient(selectedId, Unit);
////                System.out.println(StoreItem.ingreId);
//            } catch (NumberFormatException e) {
//                System.out.println("Error");
//            }
//        }
////      end get ingredient Id
//      Here for display data in list when add 

    }//GEN-LAST:event_btn_addActionPerformed
//here to check item exist in list or not

    private boolean isExist(String Selected) {
        for (int i = 0; i < listModel.size(); i++) {
            if (listModel.get(i).contains(Selected)) {
                return true;
            }

        }
        return false;
    }
    private void IngreNameComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreNameComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngreNameComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddIngredient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddIngredient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddIngredient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddIngredient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddIngredient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> IngreNameCombo;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_back1;
    private javax.swing.JButton btn_done;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCate;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPrice;
    private javax.swing.JTextField txt_unit;
    // End of variables declaration//GEN-END:variables
}
